### ISSUE TITLE
メンテナンス中のメッセージ

### ISSUE THREAD

**Issue by mikau** [momoxo/momoxo#2]
このサイトはただいまメインテナンスです。後程お越しください。
↓
このサイトはただいまメンテナンス中です。のちほどお越しください。

**Comment by hamaco** [comment]
多分Installerの範囲内なのでInstaller直すついでにやる

**Comment by hamaco** [comment]
新インストーラーがMergeされたので修正済みのはず:smile:

**Comment by suin** [comment]
OK 「このサイトはただいまメンテナンス中です。のちほどお越しください。」に直ってたのを確認した。
