### ISSUE TITLE
XCoreのインストーラにissystemを追加する

### ISSUE THREAD

**Issue by nouphet** [momoxo/momoxo#20]
XCoreのインストーラにissystemを追加する。

※ システム系とサードパーティ系のモジュールを判別するためのカラム。

**Comment by hamaco** [comment]
isadminは既にありますよ?

![みさわ](http://jigokuno.img.jugem.jp/20101118_1994710.gif)

**Comment by nouphet** [comment]
コアチームさんへ

issystemの間違いでした。

issystem でお願いします！

**Comment by hamaco** [comment]
タイトル変えればいいのに！ 変えればいいのに！

**Comment by nouphet** [comment]
あ、変わった。
ありがとう！

**Comment by hamaco** [comment]
assign 忘れてた＞＜

**Comment by suin** [comment]
これって、ステータスOpenのまま？Close？

**Comment by hamaco** [comment]
リーダー仕事しないからなー。 Close しちゃうか。
