### ISSUE TITLE
xcoreのrequire_onceを削除してテスタブルにする

### ISSUE THREAD

**Issue by suin** [momoxo/momoxo#33]
クラスファイルの頭でXOOPS_ROOT_PATH がないと死んだりしててテストが実行できない。

自動テストでテスタブルにするために
class map autoloader を簡易的に実装して、
require_once, include_once しなくてもいいようにする。

**Comment by suin** [comment]
取り除けるのは取り除いたのでクローズ

**Comment by hamaco** [comment]
:+1:
