### ISSUE TITLE
管理画面の install 削除して下さい, mainfile.php書き込み権限消してねの警告を出さなくする

### ISSUE THREAD

**Issue by suin** [momoxo/momoxo#37]
installerは削除しなくても問題なくなったので、警告不要。
mainfile.phpにXOOPS＿ROOT_PATHはもはやないので、mainfile.phpではなく html/config フォルダの書込権限についてのみ警告する

注意：ファイル/Users/suin/Dropbox/Suin/Projects/GitHub/momonga/html/install/がサーバ上に存在します。インストール完了後は必ず削除してください。
注意：ファイル/Users/suin/Dropbox/Suin/Projects/GitHub/momonga/html/mainfile.phpへの書き込みが可能となっています。このファイルのパーミッション設定を変更してください。

**Comment by hamaco** [comment]
これ config.php のチェックどうします? 基本的に apache 権限で作っちゃうから普通のユーザがパーミッション設定するの難しい気がしますが。

**Comment by suin** [comment]
config.phpはチェックいらなそうですね

**Comment by hamaco** [comment]
じゃあ削除します

**Comment by hamaco** [comment]
消しました。
