### ISSUE TITLE
インストールの第2画面自動実行がうごいてない

### ISSUE THREAD

**Issue by mikau** [momoxo/momoxo#44]
以下のモジュールが導入されていません

というページ。メッセージとプロテクターはデフォルト入れちゃえばOK？
そしたら1ページでインストール完了するんですが。

何か問題があるのかな？

**Comment by suin** [comment]
「インストールしています」で自動的にそこをjQueryでやってるはず。masterをgit pullしても変わらないですか？

**Comment by suin** [comment]
なぜか 503 Service Temporarily Unavailable が返ってきてて jQuery の Ajax が上手く動いてないっぽい

**Comment by suin** [comment]
タイトル「インストールの第2画面いらないんじゃないか」→「インストールの第2画面自動実行がうごいてない」に変更

**Comment by suin** [comment]
メンテナンス画面だから503出てるのか。以前に hamaco さんの修正で動いてたのはなんでだろう。

**Comment by suin** [comment]
@mikau さん、 修正したのでご確認下さい〜

**Comment by mikau** [comment]
はーい

**Comment by mikau** [comment]
pullというのがよくわからないのですがgithubのwindowsアプリでsyncして実行したところまだ第二画面が出ていました。

historyの最後がhamacoさんの「アバター編集ページが見れないのを修正」となっています＜これで合っていればpullできているということですかね。

**Comment by suin** [comment]
pullできてますね。

> まだ第二画面が出ていました。

こちらでは再現しないんですよね…。
- DBのテーブル全部消す
- html/config/config.phpを消す
- momoxoのインストーラを開き直す
- インストーラでDB情報などを入力して送信
- 「インストールしています」画面
- その後リダイレクトされて、管理者ログインした状態になってる＆モジュールのインストールが済んでいてサイトが出来上がっている

という手順・状態ですが。

**Comment by mikau** [comment]
えええと、hamacoさんの修正で直りました。
