### ISSUE TITLE
どこからでもインストーラにリダイレクトされるようにしたい

### ISSUE THREAD

**Issue by hamaco** [momoxo/momoxo#50]
インストーラー関係の作業する時とか毎回 ROOT_PATH にアクセスしないと正常にインストーラーに遷移しないのめんどくさくないっすか?

ただ、問題は開発者以外そんな機能要らないんじゃないか的な……

**Comment by argon358** [comment]
作業効率上がるなら、とりあえずβ版の時はリダイレクトする用にしちゃうとか…

**Comment by hamaco** [comment]
いや、どの程度面倒か知らないけど、やったら別に実装時間以外にデメリットないだろうしずっとそのままですよ。多分。

**Comment by suin** [comment]
運用でカバーのほうがいいかも

**Comment by hamaco** [comment]
ふむふむ、じゃあやらなくても良いか。 普段別に困らんし。

**Comment by RyujiAMANO** [comment]
±0

**Comment by hamaco** [comment]
あれ、これ閉じてなかったのか。
