### ISSUE TITLE
extras 削除したい

### ISSUE THREAD

**Issue by hamaco** [momoxo/momoxo#54]
extras とかなんか邪魔な気がするんですが削除しちゃいませんか?

**Comment by suin** [comment]
+1 いらんでしょ

**Comment by nouphet** [comment]
+1 不要
必要なものは全てストアから入れる。

**Comment by argon358** [comment]
+1
また必要になったら、その時に適宜ファイルを追加すれば良いと思うので、とりあえず削除して良いとおもいます。

**Comment by suin** [comment]
早く消したい。grep しててノイズになる。

**Comment by suin** [comment]
削除しても戻せないこともないから削除しよう。

**Comment by hamaco** [comment]
消した

**Comment by suin** [comment]
nice!

**Comment by nouphet** [comment]
+1 nice!
