### ISSUE TITLE
デフォルトテーマのロゴをクリックしたらトップに

### ISSUE THREAD

**Issue by mikau** [momoxo/momoxo#58]
デフォルトテーマのロゴをクリックしたらトップにリンクを貼って欲しいです

**Comment by argon358** [comment]
ロゴ画像をクリックすると、トップへリンクするように修正しました。
ちなみにトップページかどうかの判定のSmartyが「legacy -> xcore」の置換の影響で
<{if ! $xcore_module}>
となっています。

**Comment by mikau** [comment]
これって出来た時点でcloseしちゃっていいような気もしますが、違いますかね？どのタイミングでcloseすればいいのか
・直した人がアップしたとき
・要望した人が確認したとき

**Comment by hamaco** [comment]
chatworkで話した時の記憶だと確か、直した人以外の誰か(主に要望出した人)が確認した時じゃなかったっけ?
