### ISSUE TITLE
xupdateとprofileがシステムモジュールとして認識されていない

### ISSUE THREAD

**Issue by mikau** [momoxo/momoxo#63]
xupdateとprofileがシステムモジュールとして認識されていない

**Comment by mikau** [comment]
windowsのgithubアプリで修正したものをsyncしてみたのですが、これでpull requestということになりましたかね？

**Comment by nouphet** [comment]
pull request 来てないですね。

**Comment by mikau** [comment]
えーと、濱中さんの解析によるとmasterに入れてしまったようなんですがどうですかね~

**Comment by hamaco** [comment]
改行コードの変更っぽいのがまじってて良く分かんないですが、masterに入ってるっぽいですよ。
てなわけで Close しちゃって良いんじゃないですかねー
