### ISSUE TITLE
互換モジュールと互換レンダーを統合

### ISSUE THREAD

**Issue by mikau** [momoxo/momoxo#7]
互換モジュールと互換レンダーを統合
・互換ってなんのことかわからない
・リネーム
・バナー管理は要らない

**Comment by RyujiAMANO** [comment]
legacy, legacyRenderは統合してxcoreになりました。
バナー管理は削除されました。

**Comment by nouphet** [comment]
+1 いいね！

**Comment by RyujiAMANO** [comment]
統合すんでるのでCLOSEします
