### ISSUE TITLE
blockの並び順デフォルトを0から100に＋xoops_versionでweightを指定できるように

### ISSUE THREAD

**Issue by mikau** [momoxo/momoxo#78]
blockの並び順デフォルトを0から100にする。Facebookで話し合っていた内容を適用してみました。
＋xoops_versionでweightを指定できるようにしましたが何も指定しなければ上記のデフォルトで100になる。

という変更をblockweight というブランチでしました

**Comment by hamaco** [comment]
これってマージされてるからもう閉じて良いIssueだっけ?

**Comment by RyujiAMANO** [comment]
合宿中にマージしたはずだね。閉じましょう
